version: '3'
services:
  app:
    build: .
    container_name: node_container
    image: node_image
    restart: always
    ports: 
      - '8000:8000'
    links: 
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    container_name: mongo_container